spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.H2Dialect

  sql: # 초기 스크립트 실행 여부
    init:
      mode: always
      platform: h2
  datasource:
    url: jdbc:h2:mem:development;MODE=MYSQL:DB_CLOSE_DELAY=-1
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console