spring:
  datasource:
    url: jdbc:h2:mem:development;MODE=MYSQL;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  sql:
    init:
      mode: never
  h2:
    console:
      enabled: true
      path: /h2-console
